[package]
name = "xkcd-with-alt-text"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
pulldown-cmark = "0.9.3"
regex = "1.10.2"
reqwest = "0.11.22"
shuttle-axum = "0.32.0"
shuttle-runtime = "0.32.0"
tokio = "1.28.2"
tracing = "0.1.40"
